# Watermarked by tc from github.com/sigil-enterprises/sigil-toolchain@v0.39.2
#
site_name: $PROJECT Documentation

theme:
  name: material
  custom_dir: docs/overrides

repo_url: https://github.com/$ORGANIZATION/$PROJECT/

site_dir: builds/site

extra:
  version:
    provider: mike

plugins:
  - mkdocstrings
