name: Badges

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [main]

permissions:
  contents: write

env:
  PAT_BADGES: ${{ secrets.PAT_SIGIL_BADGES }}
  PAT_ACTIONS_READ: ${{ secrets.PAT_SIGIL_ACTIONS_READ }}

jobs:

  badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: builds
          name: builds
          github-token: ${{ env.PAT_ACTIONS_READ }}
          run-id: ${{ github.event.workflow_run.id }}

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: builds/site/badges
          repository-name: ${{ github.repository_owner }}/badges
          target-folder: ${{ github.event.repository.name }}/${{ github.ref_name }}
          token: ${{ env.PAT_BADGES }}