name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    uses: opvance/actions/.github/workflows/build.yml@v2
    secrets:
      BADGES_TOKEN: ${{ secrets.PAT_BADGES }}
      REPOSITORIES_READ_TOKEN: ${{ secrets.PAT_ORG_REPO_READ }}