name: Pages

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

permissions:
  pages: write
  contents: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

env:
  PAT_ACTIONS_READ: ${{ secrets.PAT_SIGIL_ACTIONS_READ }}

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: builds
          name: builds
          github-token: ${{ env.PAT_ACTIONS_READ }}
          run-id: ${{ github.event.workflow_run.id }}

      - uses: JamesIves/github-pages-deploy-action@v4
        if: github.event.workflow_run.head_branch == 'main'
        with:
          folder: builds/site
          target-folder: .

      - uses: JamesIves/github-pages-deploy-action@v4
        if: github.event.workflow_run.head_branch != 'main'
        with:
          folder: builds/site
          target-folder: ${{ github.event.workflow_run.head_branch }}

      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: builds/gh-pages

      - uses: actions/upload-pages-artifact@v3
        with:
          path: builds/gh-pages

      - id: deployment
        uses: actions/deploy-pages@v4
